{{- if .Values.duckdbUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdb-ui
  labels:
    app: duckdb-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duckdb-ui
  template:
    metadata:
      {{- include "srdp.localSecretsChecksum" . | nindent 6 }}
      labels:
        app: duckdb-ui
    spec:
      {{- include "srdp.imagePullSecrets" . | nindent 6 }}
      initContainers:
        {{- include "srdp.waitForDucklakeDb" . | nindent 8 }}
      containers:
        - name: duckdb-ui
          image: {{ include "srdp.image" (list . .Values.duckdbUi.image) }}
          imagePullPolicy: {{ .Values.duckdbUi.image.pullPolicy }}
          ports:
            - containerPort: 4213
          env:
            {{- include "srdp.ducklakeEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "srdp.ducklakeVolumeMount" . | nindent 12 }}
      volumes:
        {{- include "srdp.ducklakeVolume" . | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: duckdb-ui
spec:
  selector:
    app: duckdb-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4213
{{- end }}
