{{- if .Values.hub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    app: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      containers:
        - name: hub
          image: "{{ .Values.hub.image.repository }}:{{ .Values.hub.image.tag }}"
          imagePullPolicy: {{ .Values.hub.image.pullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hub
spec:
  selector:
    app: hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
{{- end }}
