{{- if .Values.hub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    app: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      {{- include "srdp.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: hub
          image: {{ include "srdp.image" (list . .Values.hub.image) }}
          imagePullPolicy: {{ .Values.hub.image.pullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hub
spec:
  selector:
    app: hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
{{- end }}
