name: cbs_example
version: "1.0.0"
profile: cbs_example

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target"]

models:
  cbs_example:
    +database: ducklake
    staging:
      +materialized: view
    marts:
      +materialized: table
